"""create promotion control plane schema

Revision ID: daef11514007
Revises:
Create Date: 2026-08-24 11:54:10.516936
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "daef11514007"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detector_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("detector_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("detector_key", "version"),
    )
    op.create_table(
        "evaluator_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evaluator_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("evaluator_type", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluator_key", "version"),
    )
    op.create_table(
        "idempotency_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "idempotency_key"),
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("minimum_weighted_score", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("required_lifecycle_approvals", sa.Integer(), nullable=False),
        sa.Column("lifecycle_stages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_key", "version"),
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("trigger_owner", sa.String(length=160), nullable=False),
        sa.Column("trigger_mode", sa.String(length=80), nullable=False),
        sa.Column("owner_reference", sa.String(length=300), nullable=False),
        sa.Column("connection_state", sa.String(length=40), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("schedule_expression", sa.String(length=120), nullable=False),
        sa.Column("last_observed_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_expected_trigger_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_window_seconds", sa.Integer(), nullable=False),
        sa.Column("metadata_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_key"),
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("candidate_type", sa.String(length=80), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("discovered_by", sa.String(length=160), nullable=False),
        sa.Column("detector_revision_id", sa.Uuid(), nullable=True),
        sa.Column("discovery_source", sa.String(length=160), nullable=False),
        sa.Column("proposed_capability", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("active_policy_id", sa.Uuid(), nullable=True),
        sa.Column("current_policy_version", sa.String(length=40), nullable=True),
        sa.Column("current_evaluation_snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("readiness_percentage", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_policy_id"],
            ["policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["detector_revision_id"],
            ["detector_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_candidates_stage_status", "candidates", ["stage", "status"], unique=False)
    op.create_index("ix_candidates_updated_at", "candidates", ["updated_at"], unique=False)
    op.create_table(
        "criteria",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("evaluator_type", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("hard_gate", sa.Boolean(), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("comparison_operator", sa.String(length=8), nullable=False),
        sa.Column("weight", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("minimum_samples", sa.Integer(), nullable=False),
        sa.Column("required_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("aggregation_rule", sa.String(length=40), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "criterion_key"),
    )
    op.create_index(op.f("ix_criteria_policy_id"), "criteria", ["policy_id"], unique=False)
    op.create_table(
        "detector_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("detector_revision_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signals_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["detector_revision_id"],
            ["detector_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detector_runs_detector_revision_id"),
        "detector_runs",
        ["detector_revision_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_job_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("triggered_by", sa.String(length=160), nullable=False),
        sa.Column("trigger_source", sa.String(length=80), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_event_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["scheduled_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "trigger_idempotency_key"),
    )
    op.create_index(
        "ix_scheduled_job_runs_claim",
        "scheduled_job_runs",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_job_runs_job_id"), "scheduled_job_runs", ["job_id"], unique=False
    )
    op.create_table(
        "blockers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recovery", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_by", sa.String(length=160), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_blockers_active", "blockers", ["candidate_id", "cleared_at"], unique=False)
    op.create_table(
        "candidate_components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("component_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "component_type", "version"),
    )
    op.create_index(
        op.f("ix_candidate_components_candidate_id"),
        "candidate_components",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("decision_type", sa.String(length=40), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("evaluation_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decisions_candidate_created", "decisions", ["candidate_id", "created_at"], unique=False
    )
    op.create_table(
        "detector_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("detector_run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("signal_type", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(["detector_run_id"], ["detector_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detector_evidence_candidate_id"),
        "detector_evidence",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detector_evidence_detector_run_id"),
        "detector_evidence",
        ["detector_run_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "version"),
    )
    op.create_index(
        op.f("ix_evaluation_plans_candidate_id"), "evaluation_plans", ["candidate_id"], unique=False
    )
    op.create_index(
        "uq_evaluation_plans_one_active_candidate",
        "evaluation_plans",
        ["candidate_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "policy_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.String(length=160), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_assignments_candidate_id"),
        "policy_assignments",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_assignments_policy_id"), "policy_assignments", ["policy_id"], unique=False
    )
    op.create_table(
        "promoted_agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("registry_key", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id"),
        sa.UniqueConstraint("registry_key"),
    )
    op.create_table(
        "promotion_lifecycle_approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("target_stage", sa.String(length=32), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("evaluation_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"]),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promotion_lifecycle_approvals_candidate_id"),
        "promotion_lifecycle_approvals",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_plan_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_id", sa.Uuid(), nullable=False),
        sa.Column("evaluator_key", sa.String(length=120), nullable=False),
        sa.Column("evaluator_version", sa.String(length=40), nullable=False),
        sa.Column("evaluator_hash", sa.String(length=64), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["criteria.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["evaluation_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "criterion_id"),
    )
    op.create_index(
        op.f("ix_evaluation_plan_items_plan_id"), "evaluation_plan_items", ["plan_id"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["evaluation_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_idempotency_key"),
    )
    op.create_index(
        op.f("ix_evaluation_runs_candidate_id"), "evaluation_runs", ["candidate_id"], unique=False
    )
    op.create_index(
        "ix_evaluation_runs_claim",
        "evaluation_runs",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_runs_plan_id"), "evaluation_runs", ["plan_id"], unique=False
    )
    op.create_table(
        "registry_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("operation_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("publication_token", sa.String(length=64), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("evaluation_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_event_id", sa.Uuid(), nullable=True),
        sa.Column("request_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=120), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("external_version_id", sa.String(length=200), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publication_token"),
    )
    op.create_index(
        op.f("ix_registry_operations_candidate_id"),
        "registry_operations",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        "ix_registry_operations_claim",
        "registry_operations",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "uq_registry_operations_one_active_candidate",
        "registry_operations",
        ["candidate_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("promoted_agent_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("registry_operation_id", sa.Uuid(), nullable=False),
        sa.Column("publication_token", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("evaluation_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("external_version_id", sa.String(length=200), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "promoted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promoted_agent_id"],
            ["promoted_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registry_operation_id"],
            ["registry_operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publication_token"),
        sa.UniqueConstraint("registry_operation_id"),
    )
    op.create_index(
        op.f("ix_agent_versions_promoted_agent_id"),
        "agent_versions",
        ["promoted_agent_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_id", sa.Uuid(), nullable=False),
        sa.Column("measurement_type", sa.String(length=40), nullable=False),
        sa.Column("measurement_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("measurement_unit", sa.String(length=40), nullable=True),
        sa.Column("normalized_score", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("latency_ms", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("evidence_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("measurements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["criteria.id"],
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_results_criterion_id"),
        "evaluation_results",
        ["criterion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_results_evaluation_run_id"),
        "evaluation_results",
        ["evaluation_run_id"],
        unique=False,
    )
    op.create_table(
        "evidence_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=True),
        sa.Column("artifact_type", sa.String(length=80), nullable=False),
        sa.Column("uri", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("sanitized", sa.Boolean(), nullable=False),
        sa.Column("metadata_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["evaluation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_artifacts_candidate_id"),
        "evidence_artifacts",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "promotion_events",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_job_run_id", sa.Uuid(), nullable=True),
        sa.Column("registry_operation_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_promotion_events_candidate_id"), "promotion_events", ["candidate_id"], unique=False
    )
    op.create_index(
        "ix_promotion_events_candidate_sequence",
        "promotion_events",
        ["candidate_id", "sequence"],
        unique=False,
    )
    op.create_index(
        "ix_promotion_events_correlation", "promotion_events", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_promotion_events_correlation_id"),
        "promotion_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_table(
        "external_event_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("sink_key", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_sequence"],
            ["promotion_events.sequence"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_sequence", "sink_key"),
    )
    op.create_index(
        op.f("ix_external_event_deliveries_event_sequence"),
        "external_event_deliveries",
        ["event_sequence"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION reject_promotion_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          RAISE EXCEPTION 'promotion_events is append-only'
            USING ERRCODE = '55000';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER promotion_events_append_only
        BEFORE UPDATE OR DELETE ON promotion_events
        FOR EACH ROW EXECUTE FUNCTION reject_promotion_event_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER promotion_events_reject_truncate
        BEFORE TRUNCATE ON promotion_events
        FOR EACH STATEMENT EXECUTE FUNCTION reject_promotion_event_mutation()
        """
    )
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON promotion_events FROM PUBLIC")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_external_event_deliveries_event_sequence"), table_name="external_event_deliveries"
    )
    op.drop_table("external_event_deliveries")
    op.execute("DROP TRIGGER IF EXISTS promotion_events_reject_truncate ON promotion_events")
    op.execute("DROP TRIGGER IF EXISTS promotion_events_append_only ON promotion_events")
    op.execute("DROP FUNCTION IF EXISTS reject_promotion_event_mutation()")
    op.drop_index(op.f("ix_promotion_events_correlation_id"), table_name="promotion_events")
    op.drop_index("ix_promotion_events_correlation", table_name="promotion_events")
    op.drop_index("ix_promotion_events_candidate_sequence", table_name="promotion_events")
    op.drop_index(op.f("ix_promotion_events_candidate_id"), table_name="promotion_events")
    op.drop_table("promotion_events")
    op.drop_index(op.f("ix_evidence_artifacts_candidate_id"), table_name="evidence_artifacts")
    op.drop_table("evidence_artifacts")
    op.drop_index(op.f("ix_evaluation_results_evaluation_run_id"), table_name="evaluation_results")
    op.drop_index(op.f("ix_evaluation_results_criterion_id"), table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_agent_versions_promoted_agent_id"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_index("ix_registry_operations_claim", table_name="registry_operations")
    op.drop_index(op.f("ix_registry_operations_candidate_id"), table_name="registry_operations")
    op.drop_table("registry_operations")
    op.drop_index(op.f("ix_evaluation_runs_plan_id"), table_name="evaluation_runs")
    op.drop_index("ix_evaluation_runs_claim", table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_candidate_id"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_evaluation_plan_items_plan_id"), table_name="evaluation_plan_items")
    op.drop_table("evaluation_plan_items")
    op.drop_index(
        op.f("ix_promotion_lifecycle_approvals_candidate_id"),
        table_name="promotion_lifecycle_approvals",
    )
    op.drop_table("promotion_lifecycle_approvals")
    op.drop_table("promoted_agents")
    op.drop_index(op.f("ix_policy_assignments_policy_id"), table_name="policy_assignments")
    op.drop_index(op.f("ix_policy_assignments_candidate_id"), table_name="policy_assignments")
    op.drop_table("policy_assignments")
    op.drop_index(op.f("ix_evaluation_plans_candidate_id"), table_name="evaluation_plans")
    op.drop_table("evaluation_plans")
    op.drop_index(op.f("ix_detector_evidence_detector_run_id"), table_name="detector_evidence")
    op.drop_index(op.f("ix_detector_evidence_candidate_id"), table_name="detector_evidence")
    op.drop_table("detector_evidence")
    op.drop_index("ix_decisions_candidate_created", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_candidate_components_candidate_id"), table_name="candidate_components")
    op.drop_table("candidate_components")
    op.drop_index("ix_blockers_active", table_name="blockers")
    op.drop_table("blockers")
    op.drop_index(op.f("ix_scheduled_job_runs_job_id"), table_name="scheduled_job_runs")
    op.drop_index("ix_scheduled_job_runs_claim", table_name="scheduled_job_runs")
    op.drop_table("scheduled_job_runs")
    op.drop_index(op.f("ix_detector_runs_detector_revision_id"), table_name="detector_runs")
    op.drop_table("detector_runs")
    op.drop_index(op.f("ix_criteria_policy_id"), table_name="criteria")
    op.drop_table("criteria")
    op.drop_index("ix_candidates_updated_at", table_name="candidates")
    op.drop_index("ix_candidates_stage_status", table_name="candidates")
    op.drop_table("candidates")
    op.drop_table("scheduled_jobs")
    op.drop_table("policies")
    op.drop_table("idempotency_receipts")
    op.drop_table("evaluator_revisions")
    op.drop_table("detector_revisions")
    # ### end Alembic commands ###
